// <auto-generated />
using System;
using MatReceptAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatReceptAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MatReceptAPI.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mjöl",
                            Quantity = 3m,
                            RecipeId = 1,
                            Unit = "dl"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mjölk",
                            Quantity = 6m,
                            RecipeId = 1,
                            Unit = "dl"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ägg",
                            Quantity = 3m,
                            RecipeId = 1,
                            Unit = "st"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Salt",
                            Quantity = 0.5m,
                            RecipeId = 1,
                            Unit = "tsk"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Köttfärs",
                            Quantity = 500m,
                            RecipeId = 2,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Krossade tomater",
                            Quantity = 400m,
                            RecipeId = 2,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Lök",
                            Quantity = 1m,
                            RecipeId = 2,
                            Unit = "st"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Vitlök",
                            Quantity = 2m,
                            RecipeId = 2,
                            Unit = "klyftor"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Pasta",
                            Quantity = 400m,
                            RecipeId = 2,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Laxfilé",
                            Quantity = 400m,
                            RecipeId = 3,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Citron",
                            Quantity = 1m,
                            RecipeId = 3,
                            Unit = "st"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Dill",
                            Quantity = 1m,
                            RecipeId = 3,
                            Unit = "dl"
                        });
                });

            modelBuilder.Entity("MatReceptAPI.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CookTimeMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CookTimeMinutes = 20,
                            CreatedAt = new DateTime(2024, 3, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Klassiska svenska pannkakor",
                            Difficulty = "Easy",
                            Instructions = "[\"Vispa ihop mj\\u00F6l, mj\\u00F6lk och \\u00E4gg till en sl\\u00E4t smet\",\"L\\u00E5t vila 30 minuter\",\"Stek i sm\\u00F6r i het stekpanna\"]",
                            Name = "Pannkakor",
                            PrepTimeMinutes = 10,
                            Servings = 4
                        },
                        new
                        {
                            Id = 2,
                            CookTimeMinutes = 30,
                            CreatedAt = new DateTime(2024, 3, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Enkel och god köttfärssås med pasta",
                            Difficulty = "Easy",
                            Instructions = "[\"Bryn k\\u00F6ttf\\u00E4rsen i en stekpanna\",\"Hacka och fr\\u00E4s l\\u00F6k och vitl\\u00F6k\",\"Tills\\u00E4tt krossade tomater och kryddor\",\"L\\u00E5t sjuda i 20 minuter\",\"Koka pastan enligt f\\u00F6rpackningen\"]",
                            Name = "Köttfärssås",
                            PrepTimeMinutes = 15,
                            Servings = 4
                        },
                        new
                        {
                            Id = 3,
                            CookTimeMinutes = 25,
                            CreatedAt = new DateTime(2024, 3, 16, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ugnsrostad lax med citron och dill",
                            Difficulty = "Medium",
                            Instructions = "[\"S\\u00E4tt ugnen p\\u00E5 200 grader\",\"L\\u00E4gg laxen i en ugnsform\",\"Krydda med salt, peppar, citron och dill\",\"Tillaga i ugnen i ca 25 minuter\"]",
                            Name = "Laxfilé i ugn",
                            PrepTimeMinutes = 10,
                            Servings = 2
                        });
                });

            modelBuilder.Entity("MatReceptAPI.Models.Ingredient", b =>
                {
                    b.HasOne("MatReceptAPI.Models.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MatReceptAPI.Models.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
